/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/vlzs4x1KFML
 */
import { Button } from "@/components/ui/button"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { Input } from "@/components/ui/input"
import { Checkbox } from "@/components/ui/checkbox"

export function Component() {
  return (
    <div className="min-h-screen bg-white p-8">
      <header className="flex items-center justify-between">
        <h1 className="text-xl font-bold">LOGO</h1>
        <nav className="flex items-center space-x-4">
          <Button variant="ghost">Contact Us</Button>
          <Select>
            <SelectTrigger id="language">
              <SelectValue>EN</SelectValue>
            </SelectTrigger>
            <SelectContent position="popper">
              <SelectItem value="en">EN</SelectItem>
              <SelectItem value="fr">FR</SelectItem>
            </SelectContent>
          </Select>
          <Avatar>
            <AvatarImage alt="User Avatar" src="/placeholder.svg?height=32&width=32" />
            <AvatarFallback>U</AvatarFallback>
          </Avatar>
          <BellIcon className="w-6 h-6 text-gray-600" />
          <TextIcon className="w-6 h-6 text-gray-600" />
        </nav>
      </header>
      <main className="mt-12 flex justify-between">
        <section className="w-1/2 space-y-6">
          <h2 className="text-5xl font-bold leading-tight">
            Create an AIbot that serves your sales teams and your customer support
          </h2>
          <p className="text-lg">Support at every step of the way.</p>
          <div className="flex space-x-4">
            <Button variant="default">What can you do?</Button>
            <Button variant="outline">Learn about customer's team</Button>
            <Button variant="secondary">Sell it now</Button>
          </div>
        </section>
        <section className="w-1/3 bg-white rounded-xl shadow-lg p-8 space-y-4">
          <h3 className="text-xl font-semibold">Account creation</h3>
          <form className="space-y-4">
            <div className="flex flex-col space-y-1">
              <label className="text-sm font-medium" htmlFor="email">
                Email address
              </label>
              <Input id="email" placeholder="hello@uiux.com" type="email" />
            </div>
            <div className="flex flex-col space-y-1">
              <label className="text-sm font-medium" htmlFor="password">
                Password
              </label>
              <Input id="password" placeholder="********" type="password" />
            </div>
            <Select>
              <SelectTrigger id="country">
                <SelectValue placeholder="Select country" />
              </SelectTrigger>
              <SelectContent position="popper">
                <SelectItem value="us">United States</SelectItem>
                <SelectItem value="ca">Canada</SelectItem>
              </SelectContent>
            </Select>
            <Checkbox id="terms" />
            <label className="text-sm" htmlFor="terms">
              I agree to the
              <a className="text-blue-500" href="#">
                terms and conditions
              </a>
            </label>
            <Button>Create an account</Button>
          </form>
          <div className="text-sm">
            <p>
              Already have an account?{""}
              <a className="text-blue-500" href="#">
                Sign in
              </a>
            </p>
            <p>
              <a className="text-blue-500" href="#">
                Forgot your password?
              </a>
            </p>
          </div>
        </section>
      </main>
      <footer className="absolute bottom-8 right-8">
        <SmartphoneIcon className="w-12 h-12 text-green-500" />
      </footer>
    </div>
  )
}


function BellIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9" />
      <path d="M10.3 21a1.94 1.94 0 0 0 3.4 0" />
    </svg>
  )
}


function TextIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17 6.1H3" />
      <path d="M21 12.1H3" />
      <path d="M15.1 18H3" />
    </svg>
  )
}


function SmartphoneIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="14" height="20" x="5" y="2" rx="2" ry="2" />
      <path d="M12 18h.01" />
    </svg>
  )
}
